package systemd

import (
	"context"
	"strings"
	"testing"

	"github.com/janekzieleznicki/terraform-provider-quadlet/internal/scope"
	"github.com/janekzieleznicki/terraform-provider-quadlet/internal/transport"
)

// newFakeHost returns a Fake whose RunFunc dispatches on c.Path and c.Args:
//
//	quadlet.DefaultBinary          -> exit 0, stdout "---web.service---\n[Unit]\nDescription=web\n"
//	systemd.DefaultSystemctl "show" -> exit 0, stdout showOutput
//	systemd.DefaultSystemctl "cat"  -> exit 0, stdout catOutput
//	systemd.DefaultSystemctl other  -> exit 0, empty
//	systemd.DefaultJournalctl       -> exit 0, stdout "journal line\n"
func newFakeHost(showOutput, catOutput string) *transport.Fake {
	f := transport.NewFake()
	f.RunFunc = func(c transport.Command) (transport.Result, error) {
		switch c.Path {
		case DefaultSystemctl:
			if len(c.Args) > 0 {
				switch c.Args[0] {
				case "--user":
					if len(c.Args) > 1 && c.Args[1] == "show" {
						return transport.Result{Stdout: showOutput, ExitCode: 0}, nil
					}
					if len(c.Args) > 1 && c.Args[1] == "cat" {
						return transport.Result{Stdout: catOutput, ExitCode: 0}, nil
					}
					return transport.Result{ExitCode: 0}, nil
				case "show":
					return transport.Result{Stdout: showOutput, ExitCode: 0}, nil
				case "cat":
					return transport.Result{Stdout: catOutput, ExitCode: 0}, nil
				default:
					return transport.Result{ExitCode: 0}, nil
				}
			}
		case DefaultJournalctl:
			return transport.Result{Stdout: "journal line\n", ExitCode: 0}, nil
		}
		return transport.Result{ExitCode: 0}, nil
	}
	return f
}

func TestParseShow(t *testing.T) {
	tests := []struct {
		name   string
		input  string
		expect map[string]string
	}{
		{
			name:  "real four-line capture",
			input: "LoadState=loaded\nActiveState=inactive\nSubState=dead\nUnitFileState=generated\n",
			expect: map[string]string{
				"LoadState":     "loaded",
				"ActiveState":   "inactive",
				"SubState":      "dead",
				"UnitFileState": "generated",
			},
		},
		{
			name:  "value with equals",
			input: "Environment=PODMAN_SYSTEMD_UNIT=model-daemon.service\n",
			expect: map[string]string{
				"Environment": "PODMAN_SYSTEMD_UNIT=model-daemon.service",
			},
		},
		{
			name:  "line without equals ignored",
			input: "LoadState=loaded\ninvalid-line\nActiveState=inactive\n",
			expect: map[string]string{
				"LoadState":   "loaded",
				"ActiveState": "inactive",
			},
		},
		{
			name:  "empty value",
			input: "LoadState=loaded\nUnitFileState=\n",
			expect: map[string]string{
				"LoadState":     "loaded",
				"UnitFileState": "",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ParseShow(tt.input)
			for k, v := range tt.expect {
				if got[k] != v {
					t.Errorf("key %s: expected %q, got %q", k, v, got[k])
				}
			}
		})
	}
}

func TestStripCatHeader(t *testing.T) {
	tests := []struct {
		name   string
		input  string
		expect string
	}{
		{
			name:   "with real header",
			input:  "# /run/user/1000/systemd/generator/model-daemon.service\n# Automatically generated by systemd\n# \n[Unit]\nDescription=x\n",
			expect: "[Unit]\nDescription=x\n",
		},
		{
			name:   "no header",
			input:  "[Unit]\nDescription=x\n",
			expect: "[Unit]\nDescription=x\n",
		},
		{
			name:   "comment after content survives",
			input:  "# header\n[Unit]\n# inline comment\nDescription=x\n",
			expect: "[Unit]\n# inline comment\nDescription=x\n",
		},
		{
			name:   "empty input",
			input:  "",
			expect: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := StripCatHeader(tt.input)
			if got != tt.expect {
				t.Errorf("expected %q, got %q", tt.expect, got)
			}
		})
	}
}

func TestShow_NotFound(t *testing.T) {
	f := newFakeHost("LoadState=not-found\nActiveState=inactive\nSubState=dead\nUnitFileState=\n", "")
	mgr := &Manager{Transport: f, Scope: scope.ScopeUser}

	status, err := mgr.Show(context.Background(), "x.service")
	if err != nil {
		t.Fatalf("Show failed: %v", err)
	}

	if status.Exists() {
		t.Errorf("expected Exists() == false for not-found unit")
	}
}

func TestDaemonReload_UserScope(t *testing.T) {
	f := newFakeHost("", "")
	mgr := &Manager{Transport: f, Scope: scope.ScopeUser}

	err := mgr.DaemonReload(context.Background())
	if err != nil {
		t.Fatalf("DaemonReload failed: %v", err)
	}

	// Check that a command was recorded with --user flag
	if len(f.Commands) == 0 {
		t.Fatalf("expected command to be recorded")
	}
	if f.Commands[0].Args[0] != "--user" {
		t.Errorf("expected --user flag for user scope")
	}
	if f.Commands[0].Env["XDG_RUNTIME_DIR"] != "/run/user/1000" {
		t.Errorf("expected XDG_RUNTIME_DIR in env")
	}
}

func TestDaemonReload_SystemScope(t *testing.T) {
	f := newFakeHost("", "")
	mgr := &Manager{Transport: f, Scope: scope.ScopeSystem}

	err := mgr.DaemonReload(context.Background())
	if err != nil {
		t.Fatalf("DaemonReload failed: %v", err)
	}

	// Check that no --user flag for system scope
	if len(f.Commands) == 0 {
		t.Fatalf("expected command to be recorded")
	}
	if len(f.Commands[0].Args) > 0 && f.Commands[0].Args[0] == "--user" {
		t.Errorf("expected no --user flag for system scope")
	}
	if len(f.Commands[0].Env) > 0 {
		t.Errorf("expected no XDG_RUNTIME_DIR for system scope, got %v", f.Commands[0].Env)
	}
}

func TestRestart_WithExitError(t *testing.T) {
	f := transport.NewFake()
	f.RunFunc = func(_ transport.Command) (transport.Result, error) {
		return transport.Result{ExitCode: 1, Stderr: "Job failed\n"}, nil
	}
	mgr := &Manager{Transport: f, Scope: scope.ScopeSystem}

	err := mgr.Restart(context.Background(), "x.service")
	if err == nil {
		t.Errorf("expected error, got nil")
	}
	if !strings.Contains(err.Error(), "exit 1") {
		t.Errorf("error should contain 'exit 1': %v", err)
	}
	if !strings.Contains(err.Error(), "Job failed") {
		t.Errorf("error should contain stderr: %v", err)
	}
}

func TestJournal_UserScope(t *testing.T) {
	f := newFakeHost("", "")
	mgr := &Manager{Transport: f, Scope: scope.ScopeUser}

	output, err := mgr.Journal(context.Background(), "x.service", 50)
	if err != nil {
		t.Fatalf("Journal failed: %v", err)
	}

	if output != "journal line\n" {
		t.Errorf("expected 'journal line\\n', got %q", output)
	}

	// Check journal invocation
	if len(f.Commands) == 0 {
		t.Fatalf("expected command to be recorded")
	}
	if f.Commands[0].Args[0] != "--user" {
		t.Errorf("expected --user flag for user scope")
	}
}

func TestSudo_Flag(t *testing.T) {
	f := transport.NewFake()
	mgr := &Manager{Transport: f, Scope: scope.ScopeSystem, Sudo: true}

	mgr.DaemonReload(context.Background())

	if len(f.Commands) == 0 {
		t.Fatalf("expected command to be recorded")
	}
	if !f.Commands[0].Sudo {
		t.Errorf("expected Sudo flag to be set")
	}
}
