package quadlet

import (
	"bufio"
	"path"
	"regexp"
	"strings"
)

// GeneratedUnit represents a systemd unit generated by the quadlet generator.
type GeneratedUnit struct {
	Name string // e.g. "web.service"
	Body string // unit text, exactly one trailing newline
}

// Problem represents an error reported by the quadlet generator.
type Problem struct {
	File    string // unit filename, e.g. "typo.container"
	Message string
}

// ParseGeneratedUnits parses the generator's stdout to extract generated units.
// Each unit is preceded by a delimiter of the form ---<unitname>---
// The body continues until the next delimiter or EOF.
func ParseGeneratedUnits(stdout string) []GeneratedUnit {
	var units []GeneratedUnit
	scanner := bufio.NewScanner(strings.NewReader(stdout))

	delimiterRe := regexp.MustCompile(`^---(.+)---$`)
	var currentBody []string
	var currentName string

	for scanner.Scan() {
		line := scanner.Text()

		// Check if this is a delimiter
		if matches := delimiterRe.FindStringSubmatch(line); matches != nil {
			// If we were building a previous unit, save it
			if currentName != "" {
				units = append(units, GeneratedUnit{
					Name: path.Base(currentName),
					Body: normalizeBody(currentBody),
				})
			}

			// Start a new unit
			currentName = matches[1]
			currentBody = nil
		} else if currentName != "" {
			// We're inside a unit body
			currentBody = append(currentBody, line)
		}
	}

	// Don't forget the last unit
	if currentName != "" {
		units = append(units, GeneratedUnit{
			Name: path.Base(currentName),
			Body: normalizeBody(currentBody),
		})
	}

	return units
}

// normalizeBody normalizes a unit body to end with exactly one newline.
func normalizeBody(lines []string) string {
	body := strings.Join(lines, "\n")
	body = strings.TrimRight(body, "\n")
	if body != "" {
		body += "\n"
	}
	return body
}

// ParseProblems parses the generator's stderr to extract error messages.
func ParseProblems(stderr string) []Problem {
	var problems []Problem
	scanner := bufio.NewScanner(strings.NewReader(stderr))

	// Regex to strip the prefix: quadlet-generator[<digits>]:
	prefixRe := regexp.MustCompile(`^quadlet-generator\[\d+\]: `)

	// Regex patterns for the two error shapes
	convertingRe := regexp.MustCompile(`^converting "([^"]+)": (.*)$`)
	errorLoadingRe := regexp.MustCompile(`^error loading "([^"]+)", (.*)$`)

	for scanner.Scan() {
		line := scanner.Text()

		// Strip the prefix
		strippedLine := prefixRe.ReplaceAllString(line, "")
		if strippedLine == line {
			// No prefix found, ignore this line
			continue
		}

		// Try to match the first shape
		if matches := convertingRe.FindStringSubmatch(strippedLine); matches != nil {
			problems = append(problems, Problem{
				File:    matches[1],
				Message: matches[2],
			})
			continue
		}

		// Try to match the second shape
		if matches := errorLoadingRe.FindStringSubmatch(strippedLine); matches != nil {
			problems = append(problems, Problem{
				File:    path.Base(matches[1]),
				Message: matches[2],
			})
			continue
		}

		// Ignore other lines (debug output, informational messages, etc.)
	}

	return problems
}
